# authentication credentials
credentials:
  usernames:
    mushfiq:
      email: mushfiq@gmail.com
      name: mushfiq 
      password: $2b$12$.9wlECTAivmpbLnMais66uDV0WMjjk6dWosWPXL/u81VH0.wiaQi.

cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - mushfiq@growwithdata.net


db:
  host: "localhost"
  user: "root"
  passwd: "hjkl"
  database: "expensedb"
  auth_plugin: "mysql_native_password"


email_sender:
  email: "kalim.resource@gmail.com"
  pass: "abc"